import type { BrandCatalog } from './types.js';

export const BRAND_CATALOG = {
  "version": 1,
  "updatedOn": "2026-08-28",
  "directoryUrl": "https://meathill.com/app",
  "fallbackDirectoryUrl": "https://meathill.github.io/meathill/",
  "organization": {
    "id": "https://meathill.com/#organization",
    "name": "Meathill Studio",
    "legalName": "Meathill LLC",
    "url": "https://meathill.com"
  },
  "maxDirectLinks": 6,
  "sites": [
    {
      "id": "meathill",
      "host": "meathill.com",
      "name": "Meathill Studio",
      "url": "https://meathill.com",
      "summary": "肉山的个人网站，汇总产品、技术文章和持续开发记录。",
      "type": "public-product",
      "visibility": "public",
      "brandMode": "full",
      "defaultLocale": "zh",
      "navigationGroup": "studio",
      "priority": 100
    },
    {
      "id": "evertools",
      "host": "tools.meathill.com",
      "name": "EverTools",
      "url": "https://tools.meathill.com",
      "summary": "在浏览器本地处理图片、PDF、JSON 和 Markdown，不上传原始文件。",
      "type": "public-product",
      "visibility": "public",
      "brandMode": "full",
      "defaultLocale": "en",
      "navigationGroup": "products",
      "priority": 80
    },
    {
      "id": "muimemo",
      "host": "muimemo.meathill.com",
      "name": "MuiMemo",
      "url": "https://muimemo.meathill.com",
      "summary": "说一句话记下待办，AI 按时间和场景自动整理，在合适的时候提醒你。",
      "type": "public-product",
      "visibility": "public",
      "brandMode": "hybrid",
      "defaultLocale": "zh",
      "navigationGroup": "products",
      "priority": 65
    },
    {
      "id": "muiad",
      "host": "muiad.meathill.com",
      "name": "MuiAD",
      "url": "https://muiad.meathill.com",
      "summary": "面向开发者的自托管广告网络，通过 MCP 管理产品、广告位和投放。",
      "type": "public-product",
      "visibility": "public",
      "brandMode": "full",
      "defaultLocale": "en",
      "navigationGroup": "products",
      "priority": 70
    },
    {
      "id": "hsm",
      "host": "hsm.meathill.com",
      "name": "Meathill HSM",
      "url": "https://hsm.meathill.com",
      "summary": "本地优先保存和使用敏感配置，减少密钥散落在文件和剪贴板里的风险。",
      "type": "public-product",
      "visibility": "public",
      "brandMode": "full",
      "defaultLocale": "zh",
      "navigationGroup": "products",
      "priority": 40
    },
    {
      "id": "minesweeper",
      "host": "minesweeper.meathill.com",
      "name": "扫雷",
      "url": "https://minesweeper.meathill.com",
      "summary": "保留经典规则与计时统计的在线扫雷游戏，适合桌面和移动端随时开一局。",
      "type": "experiment",
      "visibility": "public",
      "brandMode": "compact",
      "defaultLocale": "zh",
      "navigationGroup": "experiments",
      "priority": 35
    },
    {
      "id": "waka",
      "host": "waka.meathill.com",
      "name": "Waka",
      "url": "https://waka.meathill.com",
      "summary": "帮助用户积累和练习词汇的跨端应用，并提供公开下载与产品说明入口。",
      "type": "public-product",
      "visibility": "public",
      "brandMode": "full",
      "defaultLocale": "en",
      "navigationGroup": "products",
      "priority": 45
    },
    {
      "id": "app-feedback",
      "host": "feedback.meathill.com",
      "name": "App Feedback",
      "url": "https://feedback.meathill.com",
      "summary": "帮助独立开发者收集、翻译和管理来自网站与应用的用户反馈。",
      "type": "public-product",
      "visibility": "public",
      "brandMode": "full",
      "defaultLocale": "en",
      "navigationGroup": "products",
      "priority": 45
    },
    {
      "id": "everband",
      "host": "everband.meathill.com",
      "name": "Everband",
      "url": "https://everband.meathill.com",
      "summary": "帮助社区乐队管理成员、活动、排练、通知和公共事务的协作工作空间。",
      "type": "public-product",
      "visibility": "public",
      "brandMode": "full",
      "defaultLocale": "en",
      "navigationGroup": "products",
      "priority": 60
    },
    {
      "id": "everband",
      "host": "everband-app.meathill.com",
      "name": "Everband App",
      "url": "https://everband-app.meathill.com",
      "summary": "帮助社区乐队管理成员、活动、排练、通知和公共事务的协作工作空间。",
      "type": "public-product",
      "visibility": "public",
      "brandMode": "hybrid",
      "defaultLocale": "en",
      "navigationGroup": "products",
      "priority": 60
    },
    {
      "id": "vibesite",
      "host": "vibe.meathill.com",
      "name": "VibeSite",
      "url": "https://vibe.meathill.com",
      "summary": "把 AI 生成的网页文件交上来，快速获得一个真实可访问的公开链接。",
      "type": "experiment",
      "visibility": "public",
      "brandMode": "full",
      "defaultLocale": "zh",
      "navigationGroup": "experiments",
      "priority": 50
    },
    {
      "id": "muirpg",
      "host": "muirpg.meathill.com",
      "name": "MuiRPG",
      "url": "https://muirpg.meathill.com",
      "summary": "选择模组和人物卡，与 AI 一起完成遵循清晰规则、持续发展的线上跑团。",
      "type": "experiment",
      "visibility": "public",
      "brandMode": "hybrid",
      "defaultLocale": "zh",
      "navigationGroup": "experiments",
      "priority": 40
    },
    {
      "id": "mui-search.meathill.com",
      "host": "mui-search.meathill.com",
      "name": "Mui Search API",
      "url": "https://mui-search.meathill.com",
      "summary": "",
      "type": "service",
      "visibility": "unlisted",
      "brandMode": "none",
      "defaultLocale": "en",
      "navigationGroup": "none",
      "priority": 0
    },
    {
      "id": "api.muiad.meathill.com",
      "host": "api.muiad.meathill.com",
      "name": "MuiAD API",
      "url": "https://api.muiad.meathill.com",
      "summary": "",
      "type": "service",
      "visibility": "internal",
      "brandMode": "none",
      "defaultLocale": "en",
      "navigationGroup": "none",
      "priority": 0
    },
    {
      "id": "admin.muiad.meathill.com",
      "host": "admin.muiad.meathill.com",
      "name": "MuiAD Admin",
      "url": "https://admin.muiad.meathill.com",
      "summary": "",
      "type": "service",
      "visibility": "internal",
      "brandMode": "none",
      "defaultLocale": "en",
      "navigationGroup": "none",
      "priority": 0
    },
    {
      "id": "i.meathill.com",
      "host": "i.meathill.com",
      "name": "Meathill Media",
      "url": "https://i.meathill.com",
      "summary": "",
      "type": "resource",
      "visibility": "unlisted",
      "brandMode": "none",
      "defaultLocale": "en",
      "navigationGroup": "none",
      "priority": 0
    },
    {
      "id": "ii.meathill.com",
      "host": "ii.meathill.com",
      "name": "Meathill Media II",
      "url": "https://ii.meathill.com",
      "summary": "",
      "type": "resource",
      "visibility": "unlisted",
      "brandMode": "none",
      "defaultLocale": "en",
      "navigationGroup": "none",
      "priority": 0
    },
    {
      "id": "blog.meathill.com",
      "host": "blog.meathill.com",
      "name": "Meathill Blog Legacy",
      "url": "https://blog.meathill.com",
      "summary": "",
      "type": "legacy",
      "visibility": "unlisted",
      "brandMode": "none",
      "defaultLocale": "zh",
      "navigationGroup": "none",
      "priority": 0
    }
  ]
} as const satisfies BrandCatalog;
